FROM openjdk:8-jdk-alpine
VOLUME /tmp

ARG DOS_PROXY_VERSION
# ARG SPRING_PROFILES_ACTIVE
# ARG CAPACITY_SERVICE_USERNAME
# ARG CAPACITY_SERVICE_PASSWORD
# ARG CAPACITY_SERVICE_CLIENT_API_URL
# ARG DOS_SERVICE_URL
# ARG SERVER_SSL_ENABLED

ADD ./target/a2si-dos-proxy-${DOS_PROXY_VERSION}.jar dos-proxy.jar
ADD ./keystore.jks keystore.jks

# Expose 7030, the default port used for Dos Proxy
EXPOSE 7030
ENV JAVA_OPTS=""
RUN ["apk", "update"]
RUN ["apk", "add", "tzdata"]
RUN ["ln", "-f", "-s", "/usr/share/zoneinfo/Europe/London", "/etc/localtime"]
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar dos-proxy.jar" ]
