# Local Deployment - running outside of AWS and Docker
#
# Uses DosSoapClient and calls Call DoS Prod instance
# Uses CapacityServiceStubClient (in Capacity Service Client module) so no external calls to the service are made

# This is the URL for the Production DoS Instance
dos:
  service:
    url: https://www.pathwaysdos.nhs.uk/app/api/webservices

# No Configuration is needed for the Stubbed Capacity Service Client

server:
  ssl:
    enabled: false