# AWS Deployment - running outside of AWS and Docker
#
# Uses DosSoapClient and calls DoS instance in Local WireMock Server
# Uses CapacityServiceRestClient (in Capacity Service Client module) so REST calls to the Local Capacity Service will occur

# This is the URL for the Wiremock Server, serving stubbed DoS Soap responses
dos:
  service:
    url: http://127.0.0.1:7010/app/api/webservices

# This is the URL for the Local Capacity Service API - note the API username and password should be passed in every
# call by the Capacity Service client but these values are passed using runtime environment variables.
# The environment variable names are:
# "capacity.service.client.api.username" & "capacity.service.client.api.password"
capacity:
  service:
    client:
      api:
        url: http://localhost:7020/capacity


server:
  ssl:
    enabled: false